services:
  database:
    image: postgres:16-alpine
    container_name: todolist-db
    environment:
      POSTGRES_DB: db_todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "3307:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./todolist-api
    container_name: todolist-api
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db_todo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      CORS_ALLOWED_ORIGINS: http://localhost,http://nam23211.id.vn
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./todolist-fe
      args:
        VITE_SERVER_URI: /api/v1
    container_name: todolist-fe
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
