version: '3.8'

services:
  database:
    image: postgres:16-alpine
    container_name: todolist-db
    environment:
      POSTGRES_DB: db_todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "3307:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./todolist-api
    container_name: todolist-api
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db_todo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/swagger-ui.html"]
      interval: 15s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./todolist-fe
      args:
        VITE_SERVER_URI: http://backend:8080/api/v1
    container_name: todolist-fe
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data: