-- TODO
CREATE TABLE todos (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" VARCHAR(255),
    "Description" TEXT,
    "DueDate" TIMESTAMP,
    "Status" VARCHAR(50),
    "CreatedOn" TIMESTAMP,
    "ModifiedOn" TIMESTAMP
);